### PR TITLE
Cargo update + License check

### PR DESCRIPTION
**Pull request by ThomasTNO**
@grebnetiew, did a `cargo update` also validated the license mentions as they somehow deviated over time..

### CODE REVIEW

**Comment by ThomasTNO** [comment]
To do: test.

To do2: Consider replacing serde_yaml with serde_yml https://github.com/sebastienrousseau/serde_yml

**Comment by ThomasTNO** [comment]
Tested on petstore, still seems to work

**Comment by ThomasTNO** [comment]
@grebnetiew, I would suggest to look later into serde_yml. What do you think?

**Comment by grebnetiew** [comment]
> @grebnetiew, I would suggest to look later into serde_yml. What do you think?

I agree, since the `serde_yaml` crate was abandoned iirc. But this one seems a little immature in that it doesn't currently build correctly? 

https://docs.rs/crate/serde_yml/latest

image

It seems like a good new issue for someone to look into and decide on and if positive, fix.

**Pull request merged**
